name: Build Windows Executable

on:
  push:
    branches:
      - main
  release:
    types: [ created ]

jobs:
  build:
    name: Build exe with PyInstaller
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Use the version of Python you need

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller  # Add other dependencies if needed
          pip install -r requirements.txt

      - name: Build Executable
        run: |
          pyinstaller --onefile main_adb.py  
          pyinstaller --onefile main_pc.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: app
          path: dist/
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Release
        uses: "actions/create-release@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "Windows exe"
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          prerelease: true
          draft: true
          body: |
            main_adb.exe 模拟器手机adb连接
            main_pc.exe PC版
            自动构建main分支

          files: |
            dist/main_adb.exe
            dist/main_pc.exe